### ISSUE TITLE
VS SecureBoot

### ISSUE THREAD

**Issue by xynydev** [linux-immutability-tools/FsGuard#14]
What's the TL;DR on what FsGuard is/has compared to Secure Boot?

**Comment by pmnlla** [comment]
EFI Secure Boot works by comparing the EFI file on the boot partition, typically grub or wbm, to a certificate stored in the motherboard's flash, and typically provided by the manufacturer.
This way, only certain _bootloaders_ can be loaded. What happens after is not in control of Secure Boot - it is only a gatekeeper for GRUB, nothing else.
Secure boot can be very easily bypassed by a self-signed certificate and a boot entry which lets you add it to the motherboard, without using the bios.

FsGuard, on the other hand, runs after the kernel and before the system init (usually systemd, sometimes openrc or runit) and compares all vital binaries in a linux system's root to a known list of hashes for each file. If a file does not match its hash, it means the root has either been tampered with or an update has been installed unsuccessfully, and the user is encouraged to revert back to a previous state of the system.

EFI Secure Boot and FsGuard are two very different layers of system security that run at their own stages of the system bring-up procedure.

Running right after the kernel, rather than being embedded into EFI, means FsGuard is largely architecture-agnostic and can work on platforms such as Oxide's hubris, on various Linux kernel versions, and various distributions such as Fedora Atomic, OpenSUSE MicroOS, and of course VanillaOS.

**Comment by xynydev** [comment]
Thanks for clarifying!
